services:
  qnap-monitor:
    build:
      context: .
    image: qnap-monitor-one:local
    container_name: qnap-monitor-one
    restart: unless-stopped
    user: "0:0"
    env_file:
      - ./qnap.env
    ports:
      - "3300:3000"
    volumes:
      - /share:/share:ro
      - /proc:/host-proc:ro
      - /sys:/host-sys:ro
      - /etc/config:/host-etc-config:ro
      - ./data:/data
