services:
  qnap-exporter:
    image: qnap-monitor-one:dev
    build:
      context: .
      dockerfile: Dockerfile
  qnap-host-exporter:
    image: qnap-monitor-one:dev
  qnap-pcie-exporter:
    image: qnap-monitor-one:dev
  qnap-process-exporter:
    image: qnap-monitor-one:dev
  qnap-dashboard-builder:
    image: qnap-monitor-one:dev
