global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: qnap_exporter
    scrape_interval: 60s
    scrape_timeout: 25s
    static_configs:
      - targets:
          - qnap-exporter:9273

  - job_name: qnap_host_exporter
    scrape_interval: 30s
    scrape_timeout: 25s
    static_configs:
      - targets:
          - qnap-host-exporter:9274

  - job_name: qnap_pcie_exporter
    scrape_interval: 30s
    scrape_timeout: 25s
    static_configs:
      - targets:
          - qnap-pcie-exporter:9275

  - job_name: qnap_process_exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - qnap-process-exporter:9276
